// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/seventeenthearth/sudal/internal/feature/health/application (interfaces: PingUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/mock_ping_usecase.go -package=mocks github.com/seventeenthearth/sudal/internal/feature/health/application PingUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/seventeenthearth/sudal/internal/feature/health/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPingUseCase is a mock of PingUseCase interface.
type MockPingUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPingUseCaseMockRecorder
	isgomock struct{}
}

// MockPingUseCaseMockRecorder is the mock recorder for MockPingUseCase.
type MockPingUseCaseMockRecorder struct {
	mock *MockPingUseCase
}

// NewMockPingUseCase creates a new mock instance.
func NewMockPingUseCase(ctrl *gomock.Controller) *MockPingUseCase {
	mock := &MockPingUseCase{ctrl: ctrl}
	mock.recorder = &MockPingUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPingUseCase) EXPECT() *MockPingUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPingUseCase) Execute(ctx context.Context) (*domain.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].(*domain.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockPingUseCaseMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPingUseCase)(nil).Execute), ctx)
}
