// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/seventeenthearth/sudal/internal/feature/health/application"
	"github.com/seventeenthearth/sudal/internal/feature/health/data"
	"github.com/seventeenthearth/sudal/internal/feature/health/domain"
	"github.com/seventeenthearth/sudal/internal/feature/health/interface"
)

// Injectors from wire.go:

// InitializeHealthHandler initializes and returns a health handler with all its dependencies
func InitializeHealthHandler() *interfaces.Handler {
	repository := data.NewRepository()
	service := application.NewService(repository)
	handler := interfaces.NewHandler(service)
	return handler
}

// wire.go:

// HealthSet is a Wire provider set for health-related dependencies
var HealthSet = wire.NewSet(data.NewRepository, wire.Bind(new(domain.Repository), new(*data.Repository)), application.NewPingUseCase, application.NewHealthCheckUseCase, application.NewService, interfaces.NewHandler)
